In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [53]:
import warnings
warnings.filterwarnings('ignore')

In [54]:
import tensorflow as tf

gpus = tf.config.list_physical_devices('GPU')
if gpus:
    try:
        # Currently, memory growth needs to be the same across GPUs
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = tf.config.experimental.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
        tf_device = "/GPU:0"
        print("Using TensorFlow device:", tf_device)
    except RuntimeError as e:
        # Memory growth must be set before GPUs have been initialized
        print(e)
else:
    tf_device = "/CPU:0"
    print("No GPU devices found. Using TensorFlow device:", tf_device)

1 Physical GPUs, 1 Logical GPUs
Using TensorFlow device: /GPU:0

In [55]:
df = pd.read_csv('/content/qoute_dataset.csv')

In [56]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [57]:
df.shape

(3038, 2)

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3038 entries, 0 to 3037
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   quote   3038 non-null   object
 1   Author  3038 non-null   object
dtypes: object(2)
memory usage: 47.6+ KB

In [59]:
df.describe()

                                                    quote            Author
count                                                3038              3038
unique                                               3037              1005
top     A woman's heart should be so hidden in God tha...  Cassandra Clare,
freq                                                    2                92

In [60]:
df.isnull().sum().sum()

np.int64(0)

In [61]:
quotes = df['quote']

In [62]:
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [63]:
quotes = quotes.str.lower()

In [64]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices, harry, that show what we t...
2    “there are only two ways to live your life. on...
3    “the person, be it gentleman or lady, who has ...
4    “imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [65]:
# remove puctuations with an empty space

import string

translator = str.maketrans('', '', string.punctuation)

quotes = quotes.apply(lambda x: x.translate(translator))

In [66]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [67]:
# Tokenization

from tensorflow.keras.preprocessing.text import Tokenizer

In [68]:
vocab_size = 10000
tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(quotes)

In [69]:
word_index = tokenizer.word_index
len(word_index)

8978

In [70]:
list(word_index.items())[:10]

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [71]:
sequence = tokenizer.texts_to_sequences(quotes)

In [72]:
for i in range(3):
  print(quotes[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
“it is our choices harry that show what we truly are far more than our abilities”
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”

In [73]:
for i in range(3):
  print(sequence[i])

[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]

In [74]:
X = []
y = []

for seq in sequence:
  for i in range(1, len(seq)):
    input_seq = seq[:i]
    output_seq = seq[i]

    X.append(input_seq)
    y.append(output_seq)

In [75]:
X

[[713],
 [713, 62],
 [713, 62, 29],
 [713, 62, 29, 19],
 [713, 62, 29, 19, 16],
 [713, 62, 29, 19, 16, 946],
 [713, 62, 29, 19, 16, 946, 10],
 [713, 62, 29, 19, 16, 946, 10, 7],
 [713, 62, 29, 19, 16, 946, 10, 7, 5],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104],
 [713,
  62,
  29,
  19,
  16,
  946,
  10,
  7,
  5,
  1156,
  8,
  70,
  293,
  10,
  145,
  12,
  809,
  104,
  752],
 [713,
  62,
  29,
  19,
  16,
  946,
  10,
  7,
  5,
  1156,
  8,
  70,
  293,
  10,
  145,
  12,
  809,
  104,
  752,
  70],
 [947],
 [947, 7],
 [947, 7, 70],
 [947, 7, 70, 871],
 [947, 7, 70, 871, 373],
 [947, 7, 70, 871, 373, 9],
 [947, 7, 70, 871, 373, 9, 433],
 [947, 7, 70, 871, 373, 9, 433, 21],
 [947, 7, 70, 871, 373, 9, 433, 21, 19],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70],
 [1337],
 [1337, 14],
 [1337, 14, 53],
 [1337, 14, 53, 201],
 [1337, 14, 53, 201, 714],
 [1337, 14, 53, 201, 714, 3],
 [1337, 14, 53, 201, 714, 3, 81],
 [1337, 14, 53, 201, 714, 3, 81, 15],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329,
  126],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329,
  126,
  7],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329,
  126,
  7,
  5],
 [713],
 [713, 116],
 [713, 116, 12],
 [713, 116, 12, 10],
 [713, 116, 12, 10, 2462],
 [713, 116, 12, 10, 2462, 32],
 [713, 116, 12, 10, 2462, 32, 1043],
 [713, 116, 12, 10, 2462, 32, 1043, 30],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338, 119],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338, 119, 12],
 [713,
  116,
  12,
  10,
  2462,
  32,
  1043,
  30,
  82,
  13,
  601,
  11,
  5,
  74,
  1338,
  119,
  12,
  2463],
 [3679],
 [3679, 7],
 [3679, 7, 313],
 [3679, 7, 313, 753],
 [3679, 7, 313, 753, 7],
 [3679, 7, 313, 753, 7, 638],
 [3679, 7, 313, 753, 7, 638, 4],
 [3679, 7, 313, 753, 7, 638, 4, 43],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339, 54],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339, 54, 682],
 [3681],
 [3681, 13],
 [3681, 13, 3],
 [3681, 13, 3, 202],
 [3681, 13, 3, 202, 5],
 [3681, 13, 3, 202, 5, 90],
 [3681, 13, 3, 202, 5, 90, 8],
 [3681, 13, 3, 202, 5, 90, 8, 434],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202, 5],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202, 5, 90],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202, 5, 90, 8],
 [947],
 [947, 7],
 [947, 7, 144],
 [947, 7, 144, 3],
 [947, 7, 144, 3, 12],
 [947, 7, 144, 3, 12, 1340],
 [947, 7, 144, 3, 12, 1340, 17],
 [947, 7, 144, 3, 12, 1340, 17, 21],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17, 21],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17, 21, 2],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17, 21, 2, 14],
 [715],
 [715, 16],
 [715, 16, 13],
 [715, 16, 13, 1341],
 [715, 16, 13, 1341, 191],
 [715, 16, 13, 1341, 191, 51],
 [715, 16, 13, 1341, 191, 51, 415],
 [715, 16, 13, 1341, 191, 51, 415, 2464],
 [715, 16, 13, 1341, 191, 51, 415, 2464, 714],
 [715, 16, 13, 1341, 191, 51, 415, 2464, 714, 9],
 [715, 16, 13, 1341, 191, 51, 415, 2464, 714, 9, 363],
 [1044],
 [1044, 180],
 [1044, 180, 7],
 [1044, 180, 7, 39],
 [1044, 180, 7, 39, 5],
 [1044, 180, 7, 39, 5, 810],
 [1044, 180, 7, 39, 5, 810, 1342],
 [1044, 180, 7, 39, 5, 810, 1342, 2],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168, 43],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168, 43, 11],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168, 43, 11, 639],
 [1044],
 [1044, 111],
 [1044, 111, 104],
 [1044, 111, 104, 1045],
 [1044, 111, 104, 1045, 7],
 [1044, 111, 104, 1045, 7, 39],
 [1044, 111, 104, 1045, 7, 39, 2],
 [1044, 111, 104, 1045, 7, 39, 2, 50],
 [2465],
 [2465, 36],
 [2465, 36, 7],
 [2465, 36, 7, 21],
 [2465, 36, 7, 21, 2],
 [2465, 36, 7, 21, 2, 65],
 [2465, 36, 7, 21, 2, 65, 10],
 [2465, 36, 7, 21, 2, 65, 10, 47],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58, 123],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58, 123, 43],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58, 123, 43, 5],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126,
  272],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126,
  272,
  15],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126,
  272,
  15,
  161],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,

In [76]:
len(X)

85271

In [77]:
len(y)

85271

In [78]:
max_length = max(len(x) for x in X)
max_length

745

In [79]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

X_padded = pad_sequences(sequence, maxlen=max_length, padding="pre")

In [80]:
X_padded

array([[   0,    0,    0, ...,  752,   70, 2461],
       [   0,    0,    0, ...,   54,   70, 3676],
       [   0,    0,    0, ...,    7,    5, 3677],
       ...,
       [   0,    0,    0, ...,   26, 2411, 8978],
       [   0,    0,    0, ...,   17,    1,  174],
       [   0,    0,    0, ...,    3,  169,  101]], dtype=int32)

In [81]:
y = np.array(y)

In [82]:
y.shape

(85271,)

In [83]:
X_padded.shape

(3038, 745)

In [84]:
# Apply one hot encoding to y

from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y, num_classes=vocab_size)

In [85]:
y_one_hot

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [86]:
y_one_hot.shape

(85271, 10000)

## Create Models

### RNN

In [87]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,LSTM, Dense

In [88]:
embedding_dim = 50

In [89]:
# Total units you want to keep in hidden layers
rnn_units=128

In [90]:
rnn_model = Sequential()

rnn_model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_length))

rnn_model.add(SimpleRNN(units=rnn_units)) # hidden layers
rnn_model.add(Dense(units=vocab_size, activation='softmax')) # Output layers

In [91]:
rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [92]:
rnn_model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

## Create LSTM Model

In [109]:
lstm_units=128

In [110]:
lstm_model = Sequential()

lstm_model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_length))

lstm_model.add(SimpleRNN(units=lstm_units)) # hidden layers
lstm_model.add(Dense(units=vocab_size, activation='softmax')) # Output layers

In [111]:
lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [112]:
lstm_model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_7 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

# Train the model

### RNN

In [96]:
epochs = 100
batch_size = 128

In [97]:
history_rnn = rnn_model.fit(X_padded, y_one_hot, epochs=epochs, batch_size=batch_size, validation_split=0.1, verbose=1)

Epoch 1/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 6s 179ms/step - accuracy: 0.0154 - loss: 8.5062 - val_accuracy: 0.0230 - val_loss: 7.0663
Epoch 2/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 76ms/step - accuracy: 0.0278 - loss: 6.1712 - val_accuracy: 0.0822 - val_loss: 6.5346
Epoch 3/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 63ms/step - accuracy: 0.0384 - loss: 5.8555 - val_accuracy: 0.0822 - val_loss: 6.6192
Epoch 4/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0384 - loss: 5.8196 - val_accuracy: 0.0822 - val_loss: 6.6692
Epoch 5/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0315 - loss: 5.8047 - val_accuracy: 0.0822 - val_loss: 6.7437
Epoch 6/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0384 - loss: 5.8001 - val_accuracy: 0.0822 - val_loss: 6.7766
Epoch 7/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - accuracy: 0.0300 - loss: 5.7979 - val_accuracy: 0.0822 - val_loss: 6.8141
Epoch 8/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - accuracy: 0.0384 - loss: 5.7924 - val_accuracy: 0.0822 - val_loss: 6.8229
Epoch 9/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 67ms/step - accuracy: 0.0358 - loss: 5.7922 - val_accuracy: 0.0822 - val_loss: 6.8705
Epoch 10/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 72ms/step - accuracy: 0.0384 - loss: 5.7874 - val_accuracy: 0.0822 - val_loss: 6.8760
Epoch 11/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 66ms/step - accuracy: 0.0347 - loss: 5.7888 - val_accuracy: 0.0822 - val_loss: 6.9050
Epoch 12/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.0318 - loss: 5.7815 - val_accuracy: 0.0822 - val_loss: 6.9274
Epoch 13/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0384 - loss: 5.7774 - val_accuracy: 0.0822 - val_loss: 6.9501
Epoch 14/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.0446 - loss: 5.7708 - val_accuracy: 0.0822 - val_loss: 6.9648
Epoch 15/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.0512 - loss: 5.7627 - val_accuracy: 0.0822 - val_loss: 6.9707
Epoch 16/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.0461 - loss: 5.7427 - val_accuracy: 0.0724 - val_loss: 6.9913
Epoch 17/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0497 - loss: 5.7239 - val_accuracy: 0.0724 - val_loss: 7.0143
Epoch 18/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 68ms/step - accuracy: 0.0563 - loss: 5.7007 - val_accuracy: 0.0724 - val_loss: 7.0085
Epoch 19/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 63ms/step - accuracy: 0.0614 - loss: 5.6787 - val_accuracy: 0.0625 - val_loss: 7.0220
Epoch 20/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.0593 - loss: 5.6574 - val_accuracy: 0.0724 - val_loss: 7.0243
Epoch 21/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - accuracy: 0.0629 - loss: 5.6336 - val_accuracy: 0.0658 - val_loss: 7.0380
Epoch 22/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.0695 - loss: 5.6108 - val_accuracy: 0.0559 - val_loss: 7.0637
Epoch 23/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.0757 - loss: 5.5845 - val_accuracy: 0.0592 - val_loss: 7.0831
Epoch 24/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - accuracy: 0.0673 - loss: 5.5595 - val_accuracy: 0.0526 - val_loss: 7.0902
Epoch 25/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - accuracy: 0.0739 - loss: 5.5345 - val_accuracy: 0.0559 - val_loss: 7.1138
Epoch 26/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - accuracy: 0.0728 - loss: 5.5055 - val_accuracy: 0.0493 - val_loss: 7.1227
Epoch 27/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 66ms/step - accuracy: 0.0717 - loss: 5.4759 - val_accuracy: 0.0526 - val_loss: 7.1408
Epoch 28/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.0819 - loss: 5.4477 - val_accuracy: 0.0559 - val_loss: 7.1210
Epoch 29/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.0746 - loss: 5.4219 - val_accuracy: 0.0592 - val_loss: 7.1298
Epoch 30/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.0892 - loss: 5.3892 - val_accuracy: 0.0592 - val_loss: 7.1510
Epoch 31/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.0852 - loss: 5.3583 - val_accuracy: 0.0526 - val_loss: 7.1640
Epoch 32/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - accuracy: 0.0914 - loss: 5.3153 - val_accuracy: 0.0493 - val_loss: 7.1616
Epoch 33/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.0944 - loss: 5.2765 - val_accuracy: 0.0493 - val_loss: 7.1530
Epoch 34/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 71ms/step - accuracy: 0.1024 - loss: 5.2293 - val_accuracy: 0.0493 - val_loss: 7.1596
Epoch 35/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 68ms/step - accuracy: 0.0988 - loss: 5.1735 - val_accuracy: 0.0461 - val_loss: 7.1662
Epoch 36/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.1086 - loss: 5.1158 - val_accuracy: 0.0362 - val_loss: 7.2230
Epoch 37/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.1050 - loss: 5.0459 - val_accuracy: 0.0395 - val_loss: 7.2906
Epoch 38/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 67ms/step - accuracy: 0.1163 - loss: 4.9718 - val_accuracy: 0.0461 - val_loss: 7.2722
Epoch 39/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - accuracy: 0.1156 - loss: 4.8897 - val_accuracy: 0.0428 - val_loss: 7.3479
Epoch 40/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.1192 - loss: 4.7956 - val_accuracy: 0.0362 - val_loss: 7.4501
Epoch 41/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.1287 - loss: 4.7085 - val_accuracy: 0.0461 - val_loss: 7.4381
Epoch 42/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 67ms/step - accuracy: 0.1353 - loss: 4.6139 - val_accuracy: 0.0329 - val_loss: 7.5536
Epoch 43/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - accuracy: 0.1452 - loss: 4.5081 - val_accuracy: 0.0329 - val_loss: 7.7279
Epoch 44/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.1489 - loss: 4.4340 - val_accuracy: 0.0362 - val_loss: 7.7407
Epoch 45/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.1580 - loss: 4.3302 - val_accuracy: 0.0362 - val_loss: 7.8068
Epoch 46/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.1712 - loss: 4.2211 - val_accuracy: 0.0296 - val_loss: 7.8933
Epoch 47/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - accuracy: 0.1807 - loss: 4.1262 - val_accuracy: 0.0296 - val_loss: 7.9569
Epoch 48/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.1924 - loss: 4.0226 - val_accuracy: 0.0263 - val_loss: 8.0361
Epoch 49/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.2019 - loss: 3.9201 - val_accuracy: 0.0230 - val_loss: 8.1100
Epoch 50/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.2231 - loss: 3.8214 - val_accuracy: 0.0164 - val_loss: 8.1799
Epoch 51/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 70ms/step - accuracy: 0.2399 - loss: 3.7224 - val_accuracy: 0.0197 - val_loss: 8.2750
Epoch 52/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 67ms/step - accuracy: 0.2597 - loss: 3.6235 - val_accuracy: 0.0132 - val_loss: 8.3339
Epoch 53/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.2809 - loss: 3.5285 - val_accuracy: 0.0132 - val_loss: 8.3836
Epoch 54/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.2930 - loss: 3.4262 - val_accuracy: 0.0164 - val_loss: 8.4843
Epoch 55/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.3252 - loss: 3.3280 - val_accuracy: 0.0164 - val_loss: 8.5402
Epoch 56/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.3460 - loss: 3.2250 - val_accuracy: 0.0132 - val_loss: 8.6321
Epoch 57/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.3639 - loss: 3.1288 - val_accuracy: 0.0066 - val_loss: 8.7337
Epoch 58/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.3870 - loss: 3.0312 - val_accuracy: 0.0132 - val_loss: 8.7729
Epoch 59/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 67ms/step - accuracy: 0.4129 - loss: 2.9357 - val_accuracy: 0.0132 - val_loss: 8.8297
Epoch 60/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 71ms/step - accuracy: 0.4400 - loss: 2.8385 - val_accuracy: 0.0099 - val_loss: 8.8872
Epoch 61/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.4561 - loss: 2.7452 - val_accuracy: 0.0066 - val_loss: 8.9568
Epoch 62/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.4806 - loss: 2.6614 - val_accuracy: 0.0132 - val_loss: 9.0445
Epoch 63/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.5135 - loss: 2.5632 - val_accuracy: 0.0132 - val_loss: 9.0717
Epoch 64/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.5344 - loss: 2.4676 - val_accuracy: 0.0132 - val_loss: 9.1427
Epoch 65/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.5552 - loss: 2.3736 - val_accuracy: 0.0132 - val_loss: 9.1924
Epoch 66/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.5775 - loss: 2.2812 - val_accuracy: 0.0132 - val_loss: 9.2548
Epoch 67/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.6020 - loss: 2.2002 - val_accuracy: 0.0132 - val_loss: 9.3460
Epoch 68/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 70ms/step - accuracy: 0.6196 - loss: 2.1138 - val_accuracy: 0.0099 - val_loss: 9.3983
Epoch 69/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 67ms/step - accuracy: 0.6463 - loss: 2.0245 - val_accuracy: 0.0132 - val_loss: 9.4875
Epoch 70/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - accuracy: 0.6580 - loss: 1.9633 - val_accuracy: 0.0099 - val_loss: 9.4967
Epoch 71/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.6785 - loss: 1.8796 - val_accuracy: 0.0099 - val_loss: 9.5695
Epoch 72/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.7034 - loss: 1.7963 - val_accuracy: 0.0099 - val_loss: 9.6586
Epoch 73/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.7180 - loss: 1.7201 - val_accuracy: 0.0099 - val_loss: 9.7037
Epoch 74/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.7432 - loss: 1.6430 - val_accuracy: 0.0099 - val_loss: 9.7490
Epoch 75/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.7612 - loss: 1.5763 - val_accuracy: 0.0099 - val_loss: 9.8283
Epoch 76/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 71ms/step - accuracy: 0.7769 - loss: 1.5042 - val_accuracy: 0.0099 - val_loss: 9.8778
Epoch 77/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 70ms/step - accuracy: 0.7897 - loss: 1.4415 - val_accuracy: 0.0066 - val_loss: 9.9595
Epoch 78/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - accuracy: 0.7981 - loss: 1.3843 - val_accuracy: 0.0066 - val_loss: 10.0141
Epoch 79/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.8124 - loss: 1.3345 - val_accuracy: 0.0099 - val_loss: 10.0335
Epoch 80/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.8193 - loss: 1.2900 - val_accuracy: 0.0099 - val_loss: 10.0880
Epoch 81/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - accuracy: 0.8365 - loss: 1.2299 - val_accuracy: 0.0099 - val_loss: 10.1640
Epoch 82/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.8453 - loss: 1.1690 - val_accuracy: 0.0099 - val_loss: 10.2497
Epoch 83/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 68ms/step - accuracy: 0.8515 - loss: 1.1067 - val_accuracy: 0.0099 - val_loss: 10.3150
Epoch 84/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 71ms/step - accuracy: 0.8610 - loss: 1.0560 - val_accuracy: 0.0099 - val_loss: 10.3411
Epoch 85/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 71ms/step - accuracy: 0.8749 - loss: 1.0030 - val_accuracy: 0.0099 - val_loss: 10.3817
Epoch 86/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - accuracy: 0.8786 - loss: 0.9605 - val_accuracy: 0.0066 - val_loss: 10.3991
Epoch 87/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.8870 - loss: 0.9165 - val_accuracy: 0.0066 - val_loss: 10.4538
Epoch 88/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.8925 - loss: 0.8727 - val_accuracy: 0.0099 - val_loss: 10.5066
Epoch 89/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.8980 - loss: 0.8392 - val_accuracy: 0.0099 - val_loss: 10.5567
Epoch 90/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.9056 - loss: 0.8093 - val_accuracy: 0.0099 - val_loss: 10.5934
Epoch 91/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.9115 - loss: 0.7691 - val_accuracy: 0.0099 - val_loss: 10.6480
Epoch 92/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.9170 - loss: 0.7300 - val_accuracy: 0.0099 - val_loss: 10.6808
Epoch 93/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 73ms/step - accuracy: 0.9225 - loss: 0.6949 - val_accuracy: 0.0033 - val_loss: 10.6993
Epoch 94/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 69ms/step - accuracy: 0.9268 - loss: 0.6647 - val_accuracy: 0.0066 - val_loss: 10.7701
Epoch 95/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.9257 - loss: 0.6618 - val_accuracy: 0.0066 - val_loss: 10.7515
Epoch 96/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.9287 - loss: 0.6356 - val_accuracy: 0.0066 - val_loss: 10.8197
Epoch 97/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.9360 - loss: 0.6017 - val_accuracy: 0.0066 - val_loss: 10.8557
Epoch 98/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.9404 - loss: 0.5707 - val_accuracy: 0.0066 - val_loss: 10.8731
Epoch 99/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.9429 - loss: 0.5430 - val_accuracy: 0.0033 - val_loss: 10.9808
Epoch 100/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.9470 - loss: 0.5207 - val_accuracy: 0.0033 - val_loss: 10.9874

###LSTM

In [113]:
epochs = 100
batch_size = 128

In [114]:
history_lstm = lstm_model.fit(X_padded, y_one_hot, epochs=epochs, batch_size=batch_size, validation_split=0.1, verbose=1)

Epoch 1/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 8s 182ms/step - accuracy: 0.0219 - loss: 8.2991 - val_accuracy: 0.0099 - val_loss: 6.8900
Epoch 2/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 67ms/step - accuracy: 0.0304 - loss: 6.0982 - val_accuracy: 0.0822 - val_loss: 6.5465
Epoch 3/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.0384 - loss: 5.8519 - val_accuracy: 0.0822 - val_loss: 6.6362
Epoch 4/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.0304 - loss: 5.8162 - val_accuracy: 0.0822 - val_loss: 6.6877
Epoch 5/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.0384 - loss: 5.8025 - val_accuracy: 0.0822 - val_loss: 6.7519
Epoch 6/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 70ms/step - accuracy: 0.0384 - loss: 5.7974 - val_accuracy: 0.0822 - val_loss: 6.7630
Epoch 7/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 68ms/step - accuracy: 0.0384 - loss: 5.7927 - val_accuracy: 0.0822 - val_loss: 6.8192
Epoch 8/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0384 - loss: 5.7927 - val_accuracy: 0.0822 - val_loss: 6.8341
Epoch 9/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0340 - loss: 5.7880 - val_accuracy: 0.0822 - val_loss: 6.8604
Epoch 10/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0384 - loss: 5.7842 - val_accuracy: 0.0822 - val_loss: 6.8767
Epoch 11/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 66ms/step - accuracy: 0.0384 - loss: 5.7819 - val_accuracy: 0.0822 - val_loss: 6.9083
Epoch 12/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0344 - loss: 5.7742 - val_accuracy: 0.0822 - val_loss: 6.9178
Epoch 13/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0399 - loss: 5.7622 - val_accuracy: 0.0822 - val_loss: 6.9418
Epoch 14/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 107ms/step - accuracy: 0.0475 - loss: 5.7434 - val_accuracy: 0.0822 - val_loss: 6.9680
Epoch 15/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - accuracy: 0.0505 - loss: 5.7290 - val_accuracy: 0.0691 - val_loss: 6.9918
Epoch 16/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - accuracy: 0.0527 - loss: 5.7069 - val_accuracy: 0.0789 - val_loss: 7.0024
Epoch 17/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0567 - loss: 5.6863 - val_accuracy: 0.0724 - val_loss: 7.0280
Epoch 18/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0538 - loss: 5.6677 - val_accuracy: 0.0658 - val_loss: 7.0087
Epoch 19/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0596 - loss: 5.6452 - val_accuracy: 0.0592 - val_loss: 7.0434
Epoch 20/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 62ms/step - accuracy: 0.0607 - loss: 5.6250 - val_accuracy: 0.0625 - val_loss: 7.0359
Epoch 21/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0644 - loss: 5.6004 - val_accuracy: 0.0691 - val_loss: 7.0574
Epoch 22/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 3s 70ms/step - accuracy: 0.0614 - loss: 5.5766 - val_accuracy: 0.0428 - val_loss: 7.0558
Epoch 23/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - accuracy: 0.0574 - loss: 5.5522 - val_accuracy: 0.0724 - val_loss: 7.0718
Epoch 24/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0636 - loss: 5.5202 - val_accuracy: 0.0526 - val_loss: 7.0971
Epoch 25/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0684 - loss: 5.4914 - val_accuracy: 0.0592 - val_loss: 7.1215
Epoch 26/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0688 - loss: 5.4604 - val_accuracy: 0.0691 - val_loss: 7.1159
Epoch 27/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0673 - loss: 5.4216 - val_accuracy: 0.0625 - val_loss: 7.1187
Epoch 28/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0801 - loss: 5.3859 - val_accuracy: 0.0461 - val_loss: 7.1332
Epoch 29/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 67ms/step - accuracy: 0.0735 - loss: 5.3440 - val_accuracy: 0.0559 - val_loss: 7.1517
Epoch 30/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 71ms/step - accuracy: 0.0830 - loss: 5.3018 - val_accuracy: 0.0461 - val_loss: 7.1758
Epoch 31/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0881 - loss: 5.2518 - val_accuracy: 0.0559 - val_loss: 7.2125
Epoch 32/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0841 - loss: 5.2042 - val_accuracy: 0.0592 - val_loss: 7.2714
Epoch 33/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0907 - loss: 5.1502 - val_accuracy: 0.0461 - val_loss: 7.3462
Epoch 34/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.0918 - loss: 5.0985 - val_accuracy: 0.0526 - val_loss: 7.3977
Epoch 35/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0874 - loss: 6.2953 - val_accuracy: 0.0000e+00 - val_loss: 14.6151
Epoch 36/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0545 - loss: 8.5965 - val_accuracy: 0.0329 - val_loss: 8.7745
Epoch 37/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0739 - loss: 6.7080 - val_accuracy: 0.0395 - val_loss: 7.1469
Epoch 38/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 72ms/step - accuracy: 0.0867 - loss: 5.4523 - val_accuracy: 0.0329 - val_loss: 7.1752
Epoch 39/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 68ms/step - accuracy: 0.0922 - loss: 5.1536 - val_accuracy: 0.0296 - val_loss: 7.2165
Epoch 40/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.0999 - loss: 5.0222 - val_accuracy: 0.0296 - val_loss: 7.4679
Epoch 41/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.0933 - loss: 5.1028 - val_accuracy: 0.0395 - val_loss: 7.2999
Epoch 42/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.1024 - loss: 4.9106 - val_accuracy: 0.0395 - val_loss: 7.3571
Epoch 43/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.1105 - loss: 4.8085 - val_accuracy: 0.0461 - val_loss: 7.4171
Epoch 44/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 67ms/step - accuracy: 0.1123 - loss: 4.7174 - val_accuracy: 0.0428 - val_loss: 7.4712
Epoch 45/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.1185 - loss: 4.6300 - val_accuracy: 0.0329 - val_loss: 7.5157
Epoch 46/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 71ms/step - accuracy: 0.1211 - loss: 4.5439 - val_accuracy: 0.0329 - val_loss: 7.5702
Epoch 47/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - accuracy: 0.1273 - loss: 4.4586 - val_accuracy: 0.0362 - val_loss: 7.6218
Epoch 48/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 67ms/step - accuracy: 0.1339 - loss: 4.3738 - val_accuracy: 0.0296 - val_loss: 7.6667
Epoch 49/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.1394 - loss: 4.2886 - val_accuracy: 0.0263 - val_loss: 7.7307
Epoch 50/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.1507 - loss: 4.2041 - val_accuracy: 0.0230 - val_loss: 7.7996
Epoch 51/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.1624 - loss: 4.1191 - val_accuracy: 0.0197 - val_loss: 7.8627
Epoch 52/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.1690 - loss: 4.0357 - val_accuracy: 0.0230 - val_loss: 7.9286
Epoch 53/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.1800 - loss: 3.9493 - val_accuracy: 0.0230 - val_loss: 7.9954
Epoch 54/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 75ms/step - accuracy: 0.1990 - loss: 3.8671 - val_accuracy: 0.0230 - val_loss: 8.0659
Epoch 55/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 67ms/step - accuracy: 0.2143 - loss: 3.7840 - val_accuracy: 0.0230 - val_loss: 8.1246
Epoch 56/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.2260 - loss: 3.7010 - val_accuracy: 0.0230 - val_loss: 8.2010
Epoch 57/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.2399 - loss: 3.6183 - val_accuracy: 0.0263 - val_loss: 8.2798
Epoch 58/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.2520 - loss: 3.5386 - val_accuracy: 0.0197 - val_loss: 8.3460
Epoch 59/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.2608 - loss: 3.4599 - val_accuracy: 0.0230 - val_loss: 8.4165
Epoch 60/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.2732 - loss: 3.3822 - val_accuracy: 0.0263 - val_loss: 8.4768
Epoch 61/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.2985 - loss: 3.3019 - val_accuracy: 0.0230 - val_loss: 8.5523
Epoch 62/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 71ms/step - accuracy: 0.3094 - loss: 3.2228 - val_accuracy: 0.0230 - val_loss: 8.6303
Epoch 63/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - accuracy: 0.3288 - loss: 3.1420 - val_accuracy: 0.0230 - val_loss: 8.6930
Epoch 64/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.3471 - loss: 3.0636 - val_accuracy: 0.0230 - val_loss: 8.7686
Epoch 65/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.3599 - loss: 2.9920 - val_accuracy: 0.0230 - val_loss: 8.8200
Epoch 66/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.3789 - loss: 2.9197 - val_accuracy: 0.0230 - val_loss: 8.9045
Epoch 67/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.3980 - loss: 2.8480 - val_accuracy: 0.0197 - val_loss: 8.9812
Epoch 68/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.4214 - loss: 2.7704 - val_accuracy: 0.0263 - val_loss: 9.0436
Epoch 69/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 67ms/step - accuracy: 0.4345 - loss: 2.6947 - val_accuracy: 0.0230 - val_loss: 9.1195
Epoch 70/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 71ms/step - accuracy: 0.4539 - loss: 2.6250 - val_accuracy: 0.0230 - val_loss: 9.2033
Epoch 71/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 66ms/step - accuracy: 0.4788 - loss: 2.5468 - val_accuracy: 0.0164 - val_loss: 9.2825
Epoch 72/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.4963 - loss: 2.4762 - val_accuracy: 0.0230 - val_loss: 9.3620
Epoch 73/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.5121 - loss: 2.4112 - val_accuracy: 0.0197 - val_loss: 9.4320
Epoch 74/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.5304 - loss: 2.3431 - val_accuracy: 0.0164 - val_loss: 9.5103
Epoch 75/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.5486 - loss: 2.2775 - val_accuracy: 0.0197 - val_loss: 9.5710
Epoch 76/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.5604 - loss: 2.2105 - val_accuracy: 0.0164 - val_loss: 9.6357
Epoch 77/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.5794 - loss: 2.1389 - val_accuracy: 0.0132 - val_loss: 9.7215
Epoch 78/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 69ms/step - accuracy: 0.5988 - loss: 2.0699 - val_accuracy: 0.0164 - val_loss: 9.7927
Epoch 79/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 69ms/step - accuracy: 0.6130 - loss: 2.0086 - val_accuracy: 0.0132 - val_loss: 9.8819
Epoch 80/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.6255 - loss: 1.9463 - val_accuracy: 0.0197 - val_loss: 9.9434
Epoch 81/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.6394 - loss: 1.8931 - val_accuracy: 0.0132 - val_loss: 10.0028
Epoch 82/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.6478 - loss: 1.8293 - val_accuracy: 0.0132 - val_loss: 10.0693
Epoch 83/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.6704 - loss: 1.7676 - val_accuracy: 0.0164 - val_loss: 10.1162
Epoch 84/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.6811 - loss: 1.7135 - val_accuracy: 0.0132 - val_loss: 10.2064
Epoch 85/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.6986 - loss: 1.6548 - val_accuracy: 0.0132 - val_loss: 10.2568
Epoch 86/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - accuracy: 0.7081 - loss: 1.6026 - val_accuracy: 0.0066 - val_loss: 10.3505
Epoch 87/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 69ms/step - accuracy: 0.7165 - loss: 1.5502 - val_accuracy: 0.0132 - val_loss: 10.3874
Epoch 88/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 66ms/step - accuracy: 0.7352 - loss: 1.4988 - val_accuracy: 0.0066 - val_loss: 10.4540
Epoch 89/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.7476 - loss: 1.4545 - val_accuracy: 0.0099 - val_loss: 10.5522
Epoch 90/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.7601 - loss: 1.4059 - val_accuracy: 0.0066 - val_loss: 10.5976
Epoch 91/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.7681 - loss: 1.3589 - val_accuracy: 0.0066 - val_loss: 10.6630
Epoch 92/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.7868 - loss: 1.3152 - val_accuracy: 0.0066 - val_loss: 10.7146
Epoch 93/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.8003 - loss: 1.2695 - val_accuracy: 0.0099 - val_loss: 10.8057
Epoch 94/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.8098 - loss: 1.2214 - val_accuracy: 0.0099 - val_loss: 10.8511
Epoch 95/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 71ms/step - accuracy: 0.8208 - loss: 1.1770 - val_accuracy: 0.0132 - val_loss: 10.9279
Epoch 96/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 69ms/step - accuracy: 0.8332 - loss: 1.1339 - val_accuracy: 0.0099 - val_loss: 10.9861
Epoch 97/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.8427 - loss: 1.0922 - val_accuracy: 0.0099 - val_loss: 11.0441
Epoch 98/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.8508 - loss: 1.0526 - val_accuracy: 0.0099 - val_loss: 11.1289
Epoch 99/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.8599 - loss: 1.0150 - val_accuracy: 0.0066 - val_loss: 11.1900
Epoch 100/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.8661 - loss: 0.9769 - val_accuracy: 0.0132 - val_loss: 11.2449

In [116]:
# Save Models

lstm_model.save("lstm_model.h5")
rnn_model.save("rnn_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.
WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

## Prediction

In [118]:
index_to_word = {}

for word, index in word_index.items():
  index_to_word[index] = word

In [119]:
index_to_word

{1: 'the',
 2: 'you',
 3: 'to',
 4: 'and',
 5: 'a',
 6: 'i',
 7: 'is',
 8: 'of',
 9: 'that',
 10: 'it',
 11: 'in',
 12: 'be',
 13: 'not',
 14: 'are',
 15: 'your',
 16: 'have',
 17: 'for',
 18: 'but',
 19: 'we',
 20: 'if',
 21: 'what',
 22: 'with',
 23: 'all',
 24: 'love',
 25: 'can',
 26: 'my',
 27: 'when',
 28: 'will',
 29: 'as',
 30: 'who',
 31: 'do',
 32: 'or',
 33: 'me',
 34: 'he',
 35: 'they',
 36: 'life',
 37: 'one',
 38: 'was',
 39: 'like',
 40: 'there',
 41: 'people',
 42: 'on',
 43: 'its',
 44: 'at',
 45: 'so',
 46: 'never',
 47: 'no',
 48: 'them',
 49: 'dont',
 50: 'know',
 51: 'just',
 52: 'more',
 53: 'only',
 54: 'than',
 55: 'because',
 56: 'this',
 57: 'want',
 58: 'up',
 59: 'how',
 60: 'his',
 61: 'things',
 62: 'world',
 63: 'by',
 64: 'think',
 65: 'make',
 66: 'about',
 67: 'time',
 68: 'from',
 69: 'always',
 70: 'our',
 71: 'an',
 72: 'out',
 73: 'us',
 74: 'good',
 75: 'said',
 76: 'she',
 77: 'her',
 78: 'way',
 79: 'go',
 80: 'am',
 81: 'live',
 82: 'has',
 83: 'something',
 84: 'see',
 85: 'too',
 86: 'then',
 87: 'every',
 88: 'were',
 89: 'some',
 90: 'man',
 91: 'thing',
 92: 'heart',
 93: 'nothing',
 94: 'get',
 95: 'him',
 96: 'youre',
 97: 'would',
 98: 'those',
 99: 'their',
 100: 'yourself',
 101: 'other',
 102: 'let',
 103: 'into',
 104: 'without',
 105: 'much',
 106: 'im',
 107: 'could',
 108: 'had',
 109: 'someone',
 110: 'ever',
 111: 'day',
 112: 'even',
 113: 'find',
 114: 'books',
 115: 'right',
 116: 'person',
 117: 'most',
 118: 'say',
 119: 'must',
 120: 'which',
 121: 'been',
 122: 'own',
 123: 'sometimes',
 124: 'read',
 125: 'should',
 126: 'everything',
 127: 'believe',
 128: 'being',
 129: 'really',
 130: 'going',
 131: 'feel',
 132: 'come',
 133: 'give',
 134: 'may',
 135: 'where',
 136: 'book',
 137: 'thats',
 138: 'tell',
 139: 'little',
 140: 'cant',
 141: 'back',
 142: 'words',
 143: 'over',
 144: 'better',
 145: 'cannot',
 146: 'through',
 147: 'now',
 148: 'any',
 149: 'enough',
 150: 'does',
 151: 'great',
 152: 'god',
 153: 'look',
 154: 'anything',
 155: 'change',
 156: 'another',
 157: 'many',
 158: 'remember',
 159: 'best',
 160: 'down',
 161: 'true',
 162: 'still',
 163: 'did',
 164: 'need',
 165: 'mind',
 166: 'soul',
 167: 'well',
 168: 'until',
 169: 'each',
 170: 'again',
 171: 'else',
 172: 'why',
 173: 'long',
 174: 'truth',
 175: 'loved',
 176: 'keep',
 177: 'very',
 178: 'first',
 179: 'moment',
 180: 'woman',
 181: 'matter',
 182: 'doesnt',
 183: 'before',
 184: 'men',
 185: 'others',
 186: 'once',
 187: 'human',
 188: 'fear',
 189: 'end',
 190: 'around',
 191: 'ive',
 192: 'beautiful',
 193: 'happy',
 194: 'kind',
 195: 'don’t',
 196: 'die',
 197: 'girl',
 198: 'happiness',
 199: 'made',
 200: 'take',
 201: 'two',
 202: 'become',
 203: 'learn',
 204: 'myself',
 205: 'theres',
 206: 'got',
 207: 'hope',
 208: 'part',
 209: 'same',
 210: 'alone',
 211: 'pain',
 212: 'friends',
 213: 'makes',
 214: 'death',
 215: 'real',
 216: 'friend',
 217: 'inside',
 218: 'thought',
 219: 'after',
 220: 'years',
 221: 'here',
 222: 'eyes',
 223: 'wrong',
 224: 'understand',
 225: 'loves',
 226: 'lives',
 227: 'reading',
 228: 'fall',
 229: 'new',
 230: 'light',
 231: 'forever',
 232: 'while',
 233: 'dream',
 234: 'ones',
 235: 'everyone',
 236: 'living',
 237: 'youll',
 238: 'bad',
 239: 'lose',
 240: 'away',
 241: 'forget',
 242: 'shall',
 243: 'hard',
 244: 'upon',
 245: 'between',
 246: 'face',
 247: 'stop',
 248: 'write',
 249: 'dreams',
 250: 'off',
 251: 'future',
 252: 'whole',
 253: 'might',
 254: 'maybe',
 255: 'ourselves',
 256: 'hell',
 257: 'looking',
 258: 'stars',
 259: 'wanted',
 260: 'trying',
 261: 'old',
 262: 'last',
 263: 'isnt',
 264: 'courage',
 265: 'try',
 266: 'mean',
 267: 'together',
 268: 'doing',
 269: 'place',
 270: 'less',
 271: 'stay',
 272: 'theyre',
 273: 'hate',
 274: 'knows',
 275: 'earth',
 276: 'put',
 277: 'felt',
 278: 'times',
 279: 'rather',
 280: 'often',
 281: 'work',
 282: 'night',
 283: 'trust',
 284: 'grow',
 285: 'walk',
 286: 'says',
 287: 'saying',
 288: 'anyone',
 289: 'smile',
 290: 'hurt',
 291: 'story',
 292: 'listen',
 293: 'thinking',
 294: 'far',
 295: 'laugh',
 296: 'small',
 297: 'having',
 298: 'reality',
 299: 'means',
 300: 'women',
 301: 'sad',
 302: 'leave',
 303: 'these',
 304: 'head',
 305: 'music',
 306: 'i’m',
 307: 'youve',
 308: 'it’s',
 309: 'important',
 310: 'somebody',
 311: 'against',
 312: 'feeling',
 313: 'beauty',
 314: 'stand',
 315: 'hand',
 316: 'done',
 317: 'reason',
 318: 'universe',
 319: 'didnt',
 320: 'fire',
 321: 'told',
 322: 'strong',
 323: 'happens',
 324: 'sure',
 325: 'talk',
 326: 'word',
 327: 'himself',
 328: 'full',
 329: 'though',
 330: 'gone',
 331: 'worth',
 332: 'point',
 333: 'door',
 334: 'broken',
 335: 'dark',
 336: 'sit',
 337: 'wish',
 338: 'happen',
 339: 'you’re',
 340: 'least',
 341: 'past',
 342: 'comes',
 343: 'hold',
 344: 'takes',
 345: 'perfect',
 346: 'stupid',
 347: 'children',
 348: 'start',
 349: 'experience',
 350: 'power',
 351: 'yet',
 352: 'asked',
 353: 'realize',
 354: 'making',
 355: 'behind',
 356: 'left',
 357: 'wants',
 358: 'choose',
 359: 'lot',
 360: 'whatever',
 361: 'lost',
 362: 'looked',
 363: 'wont',
 364: 'knowing',
 365: 'few',
 366: 'lie',
 367: 'different',
 368: 'hear',
 369: 'afraid',
 370: 'jace',
 371: 'ask',
 372: 'home',
 373: 'harry',
 374: 'impossible',
 375: 'lies',
 376: 'open',
 377: 'easy',
 378: 'already',
 379: 'three',
 380: 'exist',
 381: 'such',
 382: 'possible',
 383: 'use',
 384: 'thoughts',
 385: 'within',
 386: 'days',
 387: '—',
 388: 'themselves',
 389: 'also',
 390: 'break',
 391: 'mistakes',
 392: 'loving',
 393: 'alive',
 394: 'next',
 395: 'happened',
 396: 'wait',
 397: 'side',
 398: 'both',
 399: 'ill',
 400: 'secret',
 401: 'deep',
 402: 'sleep',
 403: 'silence',
 404: 'either',
 405: 'suffering',
 406: 'tomorrow',
 407: 'call',
 408: 'strength',
 409: 'help',
 410: 'meant',
 411: 'knew',
 412: 'speak',
 413: 'itself',
 414: 'seen',
 415: 'found',
 416: 'pretty',
 417: 'half',
 418: 'goes',
 419: 'high',
 420: 'lived',
 421: 'darkness',
 422: 'yours',
 423: 'choice',
 424: 'forgive',
 425: 'respect',
 426: 'young',
 427: 'simple',
 428: 'close',
 429: 'kill',
 430: 'beginning',
 431: 'whats',
 432: 'perhaps',
 433: 'show',
 434: 'success',
 435: 'arent',
 436: 'mad',
 437: 'friendship',
 438: 'thousand',
 439: 'crazy',
 440: 'house',
 441: 'nobody',
 442: 'history',
 443: 'able',
 444: 'set',
 445: 'meet',
 446: 'hands',
 447: 'rest',
 448: 'answer',
 449: 'id',
 450: 'voice',
 451: 'dare',
 452: 'second',
 453: 'expect',
 454: 'war',
 455: 'free',
 456: 'room',
 457: 'seems',
 458: 'somewhere',
 459: 'care',
 460: 'couldnt',
 461: 'fight',
 462: 'known',
 463: 'lonely',
 464: 'family',
 465: 'truly',
 466: 'decide',
 467: 'year',
 468: 'black',
 469: 'unless',
 470: 'begin',
 471: 'turn',
 472: 'sun',
 473: 'body',
 474: 'today',
 475: 'enjoy',
 476: 'child',
 477: 'fact',
 478: 'worse',
 479: 'yes',
 480: 'freedom',
 481: 'mother',
 482: 'actually',
 483: 'course',
 484: 'born',
 485: 'seem',
 486: 'difference',
 487: 'dead',
 488: 'taste',
 489: 'everybody',
 490: 'peace',
 491: 'took',
 492: '–',
 493: 'stories',
 494: 'loneliness',
 495: 'art',
 496: 'imagination',
 497: 'wise',
 498: 'big',
 499: 'question',
 500: 'boy',
 501: 'learned',
 502: 'single',
 503: 'completely',
 504: 'water',
 505: 'knowledge',
 506: 'gives',
 507: 'hes',
 508: 'wisdom',
 509: 'desire',
 510: 'carry',
 511: 'gets',
 512: 'sea',
 513: 'waste',
 514: 'bear',
 515: 'father',
 516: 'girls',
 517: 'act',
 518: 'fool',
 519: 'persons',
 520: 'control',
 521: 'finally',
 522: 'apart',
 523: 'special',
 524: 'quite',
 525: 'stronger',
 526: 'imagine',
 527: 'name',
 528: 'hurts',
 529: 'minds',
 530: 'under',
 531: 'teach',
 532: 'school',
 533: 'nice',
 534: 'touch',
 535: 'wake',
 536: 'tree',
 537: 'morning',
 538: 'mine',
 539: 'ten',
 540: 'called',
 541: 'came',
 542: 'seek',
 543: 'weve',
 544: 'sense',
 545: 'getting',
 546: 'kiss',
 547: 'writing',
 548: 'needs',
 549: 'deserve',
 550: 'dance',
 551: 'front',
 552: 'greatest',
 553: 'memories',
 554: 'sky',
 555: 'joy',
 556: 'feet',
 557: 'used',
 558: 'nor',
 559: 'value',
 560: 'age',
 561: 'longer',
 562: 'wouldnt',
 563: 'certain',
 564: 'okay',
 565: 'spend',
 566: 'run',
 567: 'clary',
 568: 'arms',
 569: 'merely',
 570: 'hearts',
 571: 'blood',
 572: 'short',
 573: 'met',
 574: 'shes',
 575: 'miss',
 576: 'simply',
 577: 'thinks',
 578: 'intelligent',
 579: 'oh',
 580: 'wrote',
 581: 'brave',
 582: 'whom',
 583: 'written',
 584: 'can’t',
 585: 'cry',
 586: 'feelings',
 587: 'storm',
 588: 'anybody',
 589: 'poetry',
 590: 'wonder',
 591: 'powerful',
 592: 'magic',
 593: 'gave',
 594: 'guy',
 595: 'step',
 596: 'burn',
 597: 'moon',
 598: 'escape',
 599: 'passion',
 600: 'trees',
 601: 'pleasure',
 602: 'matters',
 603: 'fantasy',
 604: 'necessary',
 605: 'faith',
 606: 'late',
 607: 'leaves',
 608: 'drink',
 609: 'avoid',
 610: 'above',
 611: 'heard',
 612: 'along',
 613: 'travel',
 614: 'infinite',
 615: 'throw',
 616: 'library',
 617: 'questions',
 618: 'looks',
 619: 'usually',
 620: 'holding',
 621: 'youd',
 622: 'instead',
 623: 'poor',
 624: 'memory',
 625: 'hour',
 626: 'grief',
 627: 'meaning',
 628: 'becomes',
 629: 'hide',
 630: 'saw',
 631: 'weak',
 632: 'falling',
 633: 'sex',
 634: 'almost',
 635: 'play',
 636: 'shut',
 637: 'cool',
 638: 'genius',
 639: 'hot',
 640: 'deal',
 641: 'minute',
 642: 'places',
 643: 'dies',
 644: 'probably',
 645: 'coming',
 646: 'painful',
 647: 'skin',
 648: 'heaven',
 649: 'accept',
 650: 'you’ve',
 651: 'build',
 652: 'song',
 653: 'laughter',
 654: 'didn’t',
 655: 'bring',
 656: 'wind',
 657: 'remain',
 658: 'none',
 659: 'common',
 660: 'move',
 661: 'nature',
 662: 'purpose',
 663: 'money',
 664: 'waiting',
 665: 'except',
 666: 'air',
 667: 'kids',
 668: 'beyond',
 669: 'losing',
 670: 'middle',
 671: 'evil',
 672: 'tears',
 673: 'follow',
 674: 'running',
 675: 'went',
 676: 'sweet',
 677: 'bed',
 678: 'gods',
 679: 'they’re',
 680: 'لا',
 681: 'و',
 682: 'absolutely',
 683: 'fail',
 684: 'asleep',
 685: 'fairy',
 686: 'tales',
 687: 'large',
 688: 'angel',
 689: 'ready',
 690: 'tried',
 691: 'therefore',
 692: 'worst',
 693: 'mans',
 694: 'forward',
 695: 'wonderful',
 696: 'worry',
 697: 'that’s',
 698: 'present',
 699: 'forgotten',
 700: 'space',
 701: 'dying',
 702: 'whether',
 703: 'rain',
 704: 'amazing',
 705: 'road',
 706: 'count',
 707: 'kindness',
 708: 'eat',
 709: 'wasnt',
 710: 'white',
 711: 'reach',
 712: 'mouth',
 713: '“the',
 714: 'ways',
 715: '“i',
 716: 'judge',
 717: 'eye',
 718: 'sin',
 719: 'soon',
 720: 'spirit',
 721: 'across',
 722: 'lord',
 723: 'terrible',
 724: 'taken',
 725: 'silent',
 726: 'outside',
 727: 'greater',
 728: 'idea',
 729: 'humans',
 730: 'moving',
 731: 'hours',
 732: 'strange',
 733: 'education',
 734: 'sight',
 735: 'learning',
 736: 'sing',
 737: 'begins',
 738: 'fun',
 739: 'fighting',
 740: 'religion',
 741: 'form',
 742: 'paper',
 743: 'crying',
 744: 'piece',
 745: 'window',
 746: 'among',
 747: 'leaving',
 748: 'cut',
 749: 'toward',
 750: 'moments',
 751: 'songs',
 752: 'changing',
 753: 'madness',
 754: 'mess',
 755: 'enemies',
 756: 'needed',
 757: 'unhappy',
 758: 'chest',
 759: 'angry',
 760: 'problem',
 761: 'order',
 762: 'safe',
 763: 'troubles',
 764: 'trouble',
 765: 'whenever',
 766: 'someday',
 767: 'mistake',
 768: 'path',
 769: 'difficult',
 770: 'discover',
 771: 'share',
 772: 'blue',
 773: 'fell',
 774: 'please',
 775: 'interesting',
 776: 'figure',
 777: 'failure',
 778: 'hundred',
 779: 'wounds',
 780: 'given',
 781: 'fly',
 782: 'turned',
 783: 'pretend',
 784: 'telling',
 785: 'giving',
 786: 'stood',
 787: 'watch',
 788: 'glass',
 789: 'summer',
 790: 'hates',
 791: 'food',
 792: 'lips',
 793: 'protect',
 794: 'started',
 795: 'havent',
 796: 'ability',
 797: 'easier',
 798: 'ideas',
 799: 'rare',
 800: 'kissed',
 801: 'fill',
 802: 'opinion',
 803: 'instant',
 804: 'soft',
 805: 'depends',
 806: 'هو',
 807: 'sort',
 808: 'أن',
 809: 'changed',
 810: 'tea',
 811: 'anyway',
 812: 'baby',
 813: 'smiling',
 814: 'brain',
 815: 'opposite',
 816: 'indifference',
 817: 'problems',
 818: 'case',
 819: 'cup',
 820: 'attempt',
 821: 'doubt',
 822: 'ahead',
 823: 'flower',
 824: 'characters',
 825: 'rules',
 826: 'chance',
 827: 'boring',
 828: 'dragons',
 829: 'risk',
 830: 'gift',
 831: 'deeply',
 832: 'adventure',
 833: 'walls',
 834: 'guess',
 835: 'clothes',
 836: 'glory',
 837: 'taught',
 838: 'he’s',
 839: 'bird',
 840: 'fig',
 841: 'wear',
 842: 'destroy',
 843: 'actions',
 844: 'magnus',
 845: 'floor',
 846: 'hair',
 847: 'survive',
 848: 'fingers',
 849: 'force',
 850: 'ron',
 851: 'goodbye',
 852: 'rule',
 853: 'families',
 854: 'understanding',
 855: 'self',
 856: 'capable',
 857: 'fox',
 858: 'stuff',
 859: 'herself',
 860: 'burning',
 861: 'spring',
 862: 'naked',
 863: 'sorrow',
 864: 'doesn’t',
 865: 'country',
 866: 'wanting',
 867: 'talking',
 868: 'tells',
 869: 'من',
 870: 'chamber',
 871: 'choices',
 872: 'lifes',
 873: 'bravery',
 874: 'nonsense',
 875: 'lack',
 876: 'conscience',
 877: 'pride',
 878: 'reader',
 879: 'reads',
 880: 'lover',
 881: 'horrible',
 882: 'belief',
 883: 'fully',
 884: 'dumbledore',
 885: 'constantly',
 886: 'kept',
 887: 'allow',
 888: 'gold',
 889: 'car',
 890: 'cats',
 891: 'blind',
 892: 'bit',
 893: 'bigger',
 894: 'you’ll',
 895: 'sound',
 896: '2',
 897: 'deepest',
 898: 'warm',
 899: 'writer',
 900: 'greatness',
 901: 'science',
 902: 'character',
 903: 'believed',
 904: 'lucky',
 905: 'awful',
 906: 'job',
 907: 'sorry',
 908: 'hidden',
 909: 'cold',
 910: 'opinions',
 911: 'easily',
 912: 'somehow',
 913: 'complete',
 914: 'relationship',
 915: 'surprise',
 916: 'wed',
 917: 'dangerous',
 918: 'promise',
 919: 'precisely',
 920: 'realized',
 921: 'offer',
 922: 'create',
 923: 'empty',
 924: 'wild',
 925: 'sadness',
 926: 'lets',
 927: 'neither',
 928: 'hit',
 929: 'killed',
 930: 'peeta',
 931: 'i’ve',
 932: 'enemy',
 933: 'feels',
 934: 'tired',
 935: 'teacher',
 936: 'corner',
 937: 'flowers',
 938: 'missing',
 939: 'parents',
 940: 'return',
 941: 'comfort',
 942: 'suddenly',
 943: 'depression',
 944: 'eternal',
 945: 'نصف',
 946: 'created',
 947: '“it',
 948: 'theyll',
 949: 'explain',
 950: 'six',
 951: 'cause',
 952: 'admit',
 953: 'onto',
 954: 'sitting',
 955: 'happening',
 956: 'staring',
 957: 'opened',
 958: 'possibly',
 959: 'whose',
 960: 'answers',
 961: 'drive',
 962: 'differently',
 963: 'ignore',
 964: 'quiet',
 965: 'clear',
 966: 'brings',
 967: 'mate',
 968: 'yesterday',
 969: 'till',
 970: 'dogs',
 971: 'dust',
 972: 'fallen',
 973: 'lead',
 974: 'fit',
 975: 'transform',
 976: 'tessa',
 977: 'pretending',
 978: 'taking',
 979: 'date',
 980: 'list',
 981: 'she’s',
 982: 'pages',
 983: 'likes',
 984: 'understood',
 985: 'favorite',
 986: 'breath',
 987: 'pure',
 988: 'filled',
 989: 'scars',
 990: 'ordinary',
 991: 'grateful',
 992: 'literature',
 993: 'sees',
 994: 'advice',
 995: 'parts',
 996: 'simon',
 997: 'faster',
 998: 'fine',
 999: 'fate',
 1000: 'ugly',
 ...}

In [120]:
def predictor(model, tokenizer, text, max_length):

  text = text.lower()
  seq = tokenizer.texts_to_sequences([text])[0]
  padded_seq = pad_sequences([seq], maxlen=max_length, padding="pre")

  pred = model.predict(padded_seq, verbose=0)
  pred_index = np.argmax(pred)
  predicted_word = index_to_word[pred_index]

  return predicted_word

In [124]:
seed_text = 'what are you trying'

predicted_word = predictor(lstm_model, tokenizer, seed_text, max_length)
print(predicted_word)

read

In [123]:
seed_text = 'life is not only'

predicted_word = predictor(lstm_model, tokenizer, seed_text, max_length)
print(predicted_word)

learn

In [138]:
# Predict a full sentence

def generate_text(model, tokenizer, seed_text, max_length, n_words):

  for _ in range(n_words):
    predicted_word = predictor(model, tokenizer, seed_text, max_length)
    if predicted_word == "":
      break
    seed_text += " " + predicted_word
  return seed_text

In [140]:
seed_text = "The person is"

generated_text = generate_text(lstm_model, tokenizer, seed_text, max_length, 10)
print(generated_text)

The person is little as but that but at may a with of

In [141]:
seed_text = "The measured quantity"

generated_text = generate_text(lstm_model, tokenizer, seed_text, max_length, 10)
print(generated_text)

The measured quantity is little i so it that if with day is

In [143]:
import pickle

# wb -> write binary

with open("tokenizer.pkl", "wb") as f:
  pickle.dump(tokenizer, f)


with open("max_length.pkl", "wb") as f:
  pickle.dump(max_length, f)